# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, worlds!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: ServiceNow-DevOps-Agent-Artifact-Registration@1
  inputs:
    connectedServiceName: 'dev54550-NR-Project1-DevOpsCHGVelocity-ServiceNow DevOps Service Connection'
    artifactsPayload: |
      {
         "artifacts": [
            {
               "name": "artifact",
               "version": "1.$(Build.BuildId)",
               "semanticVersion": "1.$(Build.BuildId).0",
               "repositoryName": "<artifact repository name>"
            },
            {
               "name": "<artifact name>",
               "version": "1.$(Build.BuildId)",
               "semanticVersion": "1.$(Build.BuildId).0",
               "repositoryName": "<artifact repository name>"
            }
         ]
      }
- task: ServiceNow-DevOps-Server-Change-Acceleration@1
  inputs:
    connectedServiceName: 'dev54550-NR-Project1-DevOpsCHGVelocity-ServiceNow DevOps Service Connection'
    changeRequestDetails: |
      {
             "setCloseCode": false,
             "attributes": {
                              "requested_by": {
                                  "name": "test user"
                              },
                              "category": "DevOps",
                              "priority": "2",
                              "comments": "This is a sample pipeline script to be added in your change step",
                              "work_notes": "Update this to work_notes",
                              "start_date": "2022-01-05 11:59:59",
                              "end_date": "2022-01-08 11:59:59"
                           }
                          }

