# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, worlds!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: ServiceNow-DevOps-Server-Change-Acceleration@1
  inputs:
  connectedServiceName: 'dev54550-NR-Project1-DevOpsCHGVelocity-ServiceNow DevOps Service Connection'
  UpstreamJob: 'Test'
  changeRequestDetails: |
        {
            "setCloseCode" : true,
            "attributes": {
              "requested_by": {
                "name": "test user"
              },
              "start_date": "2021-01-05 08:00:00",
              "end_date": "2021-01-08 08:00:00"
            }
          }
